version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    container_name: unsplash-collection-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private_network

  backend:
    build: .
    restart: always
    depends_on:
      - db
    env_file: .env
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public'
    networks:
      - private_network

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      # Expone el puerto 80 (HTTP) del VPS al puerto 80 del contenedor Nginx
      - '80:80'
      # Eventualmente aquí también expondremos el puerto 443 para HTTPS
      # - "443:443"
    volumes:
      # Monta tu archivo de configuración de Nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - mi-red

volumes:
  postgres_data:

networks:
  private_network:
