version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    container_name: unsplash-collection-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private_network


volumes:
  postgres_data:

networks:
  private_network:
